### PR TITLE
Patterns can be saved as a project

### PR DESCRIPTION
**Pull request by nightflyer88**

### CODE REVIEW

**Comment by cibomahto** [comment]
This looks promising, however I'd like to take a different approach for the save files. There's a binary serialization class built into Qt called QDataStream that can directly store things like QLIsts of images, and should be much cleaner for storing longer animations (like, several minutes of larger size videos).

I've got a poorly implemented but working branch of PatternPaint here, that demonstrates this approach:
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/mainwindow.cpp#L479
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patterncollection.cpp#L70

**Comment by cibomahto** [comment]
To support this, I'll start by writing the unit tests written for the pattern models, and push the business logic portions of the patternCollection into libblinky.

**Comment by nightflyer88** [comment]
You are quite right, is much easier with the serialization. Here is a possibility, but is not quite good. I do not know exactly how to write Qbuffer or QbyteArray into the stream and read back again? Therefore here as QString.

**Comment by cibomahto** [comment]
I think it's better to have the objects do their own serialization. In this example, it was only storing a patterncollection, and the collection could contain multiple patterns. So it opened the file, checked what kind of pattern was stored to it:
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patterncollection.cpp#L70

Then the pattern model has it's own internal deserialize function to restore itself:
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patternframemodel.cpp#L86
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patternscrollmodel.cpp#L70

And likewise to save itself:
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patterncollection.cpp#L124
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patternframemodel.cpp#L74
https://github.com/Blinkinlabs/PatternPaint/blob/leoblinky/PatternPaint/patternscrollmodel.cpp#L58

Since the QDataStream can handle Qt-style containers and objects (specifically QList and QImage) directly, it's probably best to rely on their code since it should be stable and well tested.

Likewise, the other major element of the project, the scene (which is the controller type, fixture, and color mode) should be pulled out of the mainwindow and put into it's own class, which can then have a serialize/deserialize feature. Actually all of the loading and saving functions need to eventually live in libblinky, but we can do this in steps.

**Comment by cibomahto** [comment]
I guess the biggest trick is to avoid ever writing a QBuffer or QByteArray directly- the objects that we need to store should have better representations as higher level objects.

**Comment by nightflyer88** [comment]
Look at it, I think it is the way you mean

**Comment by cibomahto** [comment]
Yes, that seems nicer.

**Pull request closed without merging**
